### ISSUE TITLE
Graphical Issues with Vanilla Chests

### ISSUE THREAD

**Issue by thanasishadow** [DoctorFTB/StoneChest#1]
Placing a vanilla chest next to a stone chest will either turn the vanilla one invisible or make it seemingly connect with the stone chest to form a double chest. Both of these are just visual issues and they don't affect either chest on any way. Also, this only occurs when the stone chest is placed first.

[![javaw-2018-11-19-19-13-27.jpg](https://i.postimg.cc/xdn5d6Qr/javaw-2018-11-19-19-13-27.jpg)](https://postimg.cc/WdYgW6tS)
[![javaw-2018-11-19-19-18-35.jpg](https://i.postimg.cc/J7ZQbwhw/javaw-2018-11-19-19-18-35.jpg)](https://postimg.cc/pyV8H68k)
[![javaw-2018-11-19-19-18-40.jpg](https://i.postimg.cc/9F2Ybx4D/javaw-2018-11-19-19-18-40.jpg)](https://postimg.cc/0rtS200v)

**Comment by DoctorFTB** [comment]
Try 1.0.2 version after approved on CurseForge.

**Comment by DoctorFTB** [comment]
@thanasishadow

**Comment by thanasishadow** [comment]
Works perfectly.
