### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by SirGeremiah** [DoctorFTB/StoneChest#7]
I have a small custom modpack. Initially, this mod fails to load. At launch, I get "**Stone Chest (stonechest) has failed to load correctly** java.lang.reflect.InvocationTargetException: null". 

Crash report: https://pastebin.com/49CK4jpn
Log: https://pastebin.com/9gDEc3bH

**Comment by DoctorFTB** [comment]
Try 1.0.1 version.

**Comment by SirGeremiah** [comment]
That seems to have resovled the issue. Thanks!
